name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Позволяет запустить вручную из вкладки Actions

jobs:
  build:
    runs-on: windows-latest  # Виртуальная машина с Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install WiX Toolset
        run: choco install wixtoolset --no-progress -y

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build app-image with jpackage
        run: |
          jpackage --type app-image `
            --name "Lor" `
            --input target `
            --main-jar lor-1.0.0.jar `
            --main-class com.okunev.lor.Main `
            --dest target/dist `
            --win-menu --win-shortcut

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lor-windows
          path: target/dist/