name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build + jlink runtime image
        run: mvn -B clean package javafx:jlink --file pom.xml

      - name: Prepare module path for jpackage
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path target\mods
          Copy-Item target\lor-1.0.0.jar target\mods\

      - name: Build EXE with jpackage
        shell: pwsh
        run: |
          jpackage --type app-image `
            --name "Lor" `
            --module-path "target\mods" `
            --module "com.okunev.lor/com.okunev.lor.Main" `
            --runtime-image "target\app" `
            --dest "target\dist"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lor-windows
          path: target/dist/
          if-no-files-found: error