name: Deploy

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package

      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v22.3
        with:
          command: make site --overwrite
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
          conveyor_version: '22.3'
          cache_key: conveyor-v22

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lor-packages
          path: output/
          if-no-files-found: error